apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.9.1
  nodeSets:
  - name: default
    count: 2
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.store.allow_mmap: false
