apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.9.1
  nodeSets:
  - name: default
    count: 2  
    config:
      node.master: true
      node.data: true
      node.ingest: false
      node.store.allow_mmap: false 
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 1
    volumeMounts:
    - mountPath: "/var/www/html"
      name: pod-volume-html
  volumes:
  - name: pod-volume-html
    persistentVolumeClaim:
      claimName: eck-claim 
